### ISSUE TITLE
org.junit cannot be resolved.

### ISSUE THREAD

**Issue by phill0694** [profwpollock/COP-2805C-2021#1]
I think there are some others errors except the package name error.
![image](https://user-images.githubusercontent.com/78010858/106347555-6844cd80-6274-11eb-8b7e-4e5206ce5ece.png)

**Comment by profwpollock** [comment]
There is no package name error.  The correct package name is "mypkg", not "main.java.mypkg".  You have a mis-understanding with Maven: all packages of code are under src/main/java.  None of that is part of any package name.

The other errors seem be be your IDE trying to test the code without using Maven.  The missing jar file for the org.junit.junit class must be manually downloaded and added to your CLASSPATH if you don't use a build tool that does that for you.

I cannot tell what IDE you are using from the error messages shown, but I think you only need to fix up your project properties to have it know this is a Maven-based project.  Otherwise, you can tell your IDE to download the JUnit jar file and adding it to CLASSPATH.  How to do that depends on your IDE.

It might be simpler and more educational if you delete the project from your PC and start again.
